### ISSUE TITLE
Sentinel is untested

### ISSUE THREAD

**Issue by andar** [mediocregopher/radix.v2#15]
There are no tests for radix's sentinel package.

**Comment by mediocregopher** [comment]
You're right about this, I can't deny it. And the testing setup for cluster isn't super convenient either. I'd really like to get that using travis-ci, if they ever got that supporting setting up a redis cluster. So this is a good reminder that I need to refactor all of that and put some work in, thanks!

**Comment by mediocregopher** [comment]
Alright, I mildly refactored a lot of the testing to be less finicky, and made a Makefile which starts up everything needed for the testing environment.

I also implemented some basic tests for sentinel. It's been a while since I've actually used sentinel and worked at all with that package, so I don't remember all the particular edge cases. If you have any specifically you'd like me to test for please feel free to open an issue for it! Thanks!

**Comment by andar** [comment]
Thanks for the quick turnaround! I'll take a look soon.
