### ISSUE TITLE
Q: How does this relate to fzzy/radix?

### ISSUE THREAD

**Issue by viblo** [mediocregopher/radix.v2#3]
Would you suggest using this package instead of fzzy/radix at the moment, and what is your plan with it going forward?

**Comment by mediocregopher** [comment]
Hi @viblo, I'm so sorry I never got back to you on this, I never received any notifications from github, email or otherwise. There's a small section on this in the README for this project, let me know if that could use any further information. As far as suggesting you use it, yes I do. I've used this for a number of high load projects and I'm quite confident in it. From this point onwards the original radix will not be receiving any new features from me, only bug fixes and doc fixes. This project will receive both new features (if it needs any) as well as bug fixes. Hopefully this helps, again sorry this is coming so late :(
