### ISSUE TITLE
nil but return wrong type

### ISSUE THREAD

**Issue by zhaoyuxi** [mediocregopher/radix.v2#55]
calling Bytes() for "HGET". Nil means no data. But Bytes() returns error. I fix it like this:
 func (r *Resp) Bytes() ([]byte, error) {
	if r.Err != nil {
		return nil, r.Err
	} else if r.typ == Nil { //return nil not error
		return nil, nil
	} else if !r.IsType(Str) {
		return nil,errBadType
	}
        ....
}
func (r *Resp) Str() (string, error) {
	b, err := r.Bytes()
	if err != nil {
		return "", err
	}
	if b == nil { //nil will return now.
		return "", errBadType //Probably here "return "", nil" is better
	}
	return string(b), nil
}

**Comment by mediocregopher** [comment]
Hey there @zhaoyuxi I'm deliberately keeping the Nil response in these cases, because a Nil response has a different meaning th,an `""` or `[]byte(nil)` or `[]byte{}`, which are all roughly equivalent ways of saying "empty string". You can use `r.IsType(redis.Nil)` to check if a response is Nil if you're expecting that it might be.

**Comment by zhaoyuxi** [comment]
@mediocregopher A nice way.Thanks very much.
