### ISSUE TITLE
why sentinel not support multi sentinel addr

### ISSUE THREAD

**Issue by hy05190134** [mediocregopher/radix.v2#66]
RT

**Comment by mediocregopher** [comment]
Hi @hy05190134! sorry it took me so long to get back to you. The short answer is that it's because I messed up when designing the package and didn't allow for `NewClient` to take in multiple addresses. At this point it's too late to fix it without breaking the package =/

As an alternative though, I recently released [radix.v3](https://godoc.org/github.com/mediocregopher/radix.v3) for beta, and it properly supports multiple sentinels in a cluster and will retry between them if the one it's connected to goes down. I know it's not an ideal solution and I'm sorry for that, but hopefully it might be a little useful in the future. I might one day come back to v2 and add in support for multiple addresses, but I don't think I'll have time in the near future. Sorry about that.
